server:
 port: 8090
 servlet:
  context-path: /employee-service

spring:
  application:
    name: employee microservice
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl